# Cross-compilation configuration for knotify

[build]
# Default build configuration
[build.env]
passthrough = [
    "RUST_BACKTRACE",
    "RUST_LOG",
]

# Linux targets
[target.x86_64-unknown-linux-gnu]
[target.x86_64-unknown-linux-musl]
[target.aarch64-unknown-linux-gnu]
[target.aarch64-unknown-linux-musl]

# Windows targets
[target.x86_64-pc-windows-gnu]

# FreeBSD targets
[target.x86_64-unknown-freebsd]
